spring.application.name=personal-task-manager

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.ai.openai.api-key=${GEMINI_API_KEY:}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.chat.options.model=gemini-1.5-flash
